#ifndef __SONAR_PROTOCOL_H__
#define __SONAR_PROTOCOL_H__

#ifdef __cplusplus
extern "C" {
#endif

#include "main.h"

#define SONAR_PROTOCOL_SOF_HIGH 0x55U
#define SONAR_PROTOCOL_SOF_LOW 0xAAU
#define SONAR_PROTOCOL_VERSION 0x01U
#define SONAR_PROTOCOL_MAX_PAYLOAD 1024U

typedef enum
{
  SONAR_RESULT_OK = 0x00U,
  SONAR_RESULT_FAIL = 0x01U,
  SONAR_RESULT_BUSY = 0x02U,
  SONAR_RESULT_INVALID_PARAM = 0x03U,
  SONAR_RESULT_INVALID_STATE = 0x04U,
  SONAR_RESULT_CRC_ERROR = 0x05U,
  SONAR_RESULT_UNSUPPORTED = 0x06U,
  SONAR_RESULT_TIMEOUT = 0x07U,
  SONAR_RESULT_HARDWARE_ERROR = 0x08U
} SonarResultCode;

typedef enum
{
  SONAR_STATUS_IDLE = 0x00U,
  SONAR_STATUS_ZEROING = 0x01U,
  SONAR_STATUS_MOVING = 0x02U,
  SONAR_STATUS_READY = 0x03U,
  SONAR_STATUS_MEASURING = 0x04U,
  SONAR_STATUS_SCANNING = 0x05U,
  SONAR_STATUS_DEBUG_SCANNING = 0x06U,
  SONAR_STATUS_UPLOADING = 0x07U,
  SONAR_STATUS_STOPPING = 0x08U,
  SONAR_STATUS_ERROR = 0x09U
} SonarDeviceStatus;

typedef enum
{
  SONAR_CMD_GET_DEVICE_INFO = 0x01U,
  SONAR_CMD_ZEROING = 0x02U,
  SONAR_CMD_STOP = 0x03U,
  SONAR_CMD_ACK = 0x04U,
  SONAR_CMD_NACK = 0x05U,
  SONAR_CMD_CONFIG_SCAN = 0x10U,
  SONAR_CMD_START_SCAN = 0x11U,
  SONAR_CMD_SCAN_POINT = 0x12U,
  SONAR_CMD_SCAN_FINISH = 0x13U,
  SONAR_CMD_CONFIG_DEBUG = 0x20U,
  SONAR_CMD_MOVE_TO_ANGLE = 0x21U,
  SONAR_CMD_START_SINGLE_MEASURE = 0x22U,
  SONAR_CMD_WAVE_CHUNK = 0x23U,
  SONAR_CMD_WAVE_FINISH = 0x24U,
  SONAR_CMD_DISTANCE_RESULT = 0x25U,
  SONAR_CMD_START_DEBUG_SWEEP = 0x26U,
  SONAR_CMD_DEBUG_SWEEP_POINT = 0x27U,
  SONAR_CMD_DEBUG_SWEEP_FINISH = 0x28U,
  SONAR_CMD_STATUS_EVENT = 0x7FU
} SonarCommandId;

typedef struct
{
  uint8_t version;
  uint8_t command;
  uint16_t sequence;
  uint16_t payload_length;
} SonarFrameHeader;

uint16_t SonarProtocol_Crc16(const uint8_t *data, uint16_t length);

#ifdef __cplusplus
}
#endif

#endif /* __SONAR_PROTOCOL_H__ */
